delphix/performance-diagnostics

bpf/stbtrace/io.json
bpf/stbtrace/io.st
bpf/stbtrace/iscsi.json
bpf/stbtrace/iscsi.st
bpf/stbtrace/nfs.json
bpf/stbtrace/nfs.st
bpf/stbtrace/vfs.json
bpf/stbtrace/vfs.st
bpf/stbtrace/zio.json
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.json
bpf/stbtrace/zpl.st
cmd/stbrace.py
lib/bcc_helper.h
lib/bcchelper.py
lib/iterative_template.py

This pull request contains: 
1)The analytic template scripts for each analytics tracing collector
2) A json data collector 
3) iterative_template.py - a java class to provide iterative templates used in the scripts
4) stbtrace (String Template BCC Trace) - a script that generates runnable tracing scripts
from the templates and executes them
I didn't give packaging to much thought as work is in progress in that area and the files can easily be moved.  
Here is some example output:
```
$ stbtrace -h
usage: stbtrace tracer [options] 
stbtrace (String Template Bcc trace) runs bcc kernel tracing scripts used by
delphix analytics to monitor various subsystems. String templates provide a
mechanism to customize the tracers by turning collection axis on and off. Two
input files are required for …
```

open source back-end analytics collectors as GPLv2

---

.github/workflows/flake8.yml

This adds a Github action to run `flake8` against pull requests. I tested by adding the action to my fork, submitting a pull request to my fork with style errors, and confirming that the action failed. I then fixed the violations and confirmed that the action succeeded.

Run flake8 against pull requests

---

lib/bcchelper.py

The lifetime of kprobe objects in the kernel is not tied to that of the process that creates them. BCC handles this by registering a Python 'atexit' handler which detatches the probes, allowing them to be cleaned up by the kernel. When the management stack restarts, however, the analytics BCC programs are killed with a SIGTERM by systemd. The python process does not have a signal handler for this signal by default, so the process is killed without the 'atexit' handlers being run.
A simple way to resolve this issue is to install a signal handler which forces the 'atexit' handlers to be run before exiting.
**Testing:**
I tested this by running an `estat` command, killing it with a SIGTERM, and confirming that the kprobes were cleaned up by looking at …

DLPX-67298 kprobes are leaked when delphix-mgmt restarts

---

cmd/stbtrace.py

Fixed this error when running from package installation. 
delphix@guild:~$ sudo stbtrace io
Error reading ../bpf/stbtrace/io.json: No such file or directory
This also updates the collection interval to be in seconds.  The interval is converted back to nanoseconds since that is what the underlying template scripts want.  The parameter is used to convert nanoseconds to seconds.

stbtrace can't find input files for package installations, collection interval in seconds

---

bpf/estat/backend-io.c
bpf/stbtrace/io.st
cmd/estat.py

Upgrade to linux kernel 5.x breaks the backend IO collector, using `estat` or `stbtrace` fails with 
```Failed to attach BPF program disk_io_start to kprobe blk_start_request```
This is a quick fix, verified on latest trunk VM using 5.x kernel.

Fix backend io collector post 5.x kernel upgrade

---

bpf/stbtrace/io.st
cmd/estat.py

Heres the PR against `6.0/release` to fix backend io collector post 5.x kernel upgrade.

Fix backend io collector post 5.x kernel upgrade (#18)

---

bpf/estat/zpl.c
bpf/stbtrace/zpl.st
cmd/estat.py

ZFS dropped FSYNC and FDSYNC  and zfs_write now checks for O_SYNC and OD_SYNC.  Additionally, the include file in zfs_headers changed enough to cause some multiple definitions and some missing definitions. 
I ran the zpl collector for estat and stbtrace  on 4.15 and 5.0 kernels:
5.0.0-36-generic
```
$ uname -a
Linux brad-zpl.dcenter 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ sudo ./estat.py zpl -a rpool 4
12/05/19 - 23:29:31 UTC
microseconds                                         zfs_read async, 
[0, 10)                        51 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  
[10, 20)                        2 |@ …
```

Fix ZPL Collectors after ZFS changes to sync flags and include files

---

bpf/standalone/zil.py
lib/bcchelper.py

commas in the output of keys in estat
estat: too many arguments output when there are too few
estat: remove mandatory final positional duration argument

estat issues

---

bpf/stbtrace/io.st
bpf/stbtrace/iscsi.st
bpf/stbtrace/nfs.st
bpf/stbtrace/vfs.st
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
lib/bcchelper.py

Some of our scripts rely on the copy of bcc_helper.h from the app-gate. I checked that the contents of the copy in the app-gate and the copy in this repo are identical, modulo some formatting, and then switch all the scripts to rely on the copy here.
**Testing**
I removed the copy bcc_helper.h installed by the app-gate and ran each collector to make sure it compiled and produced reasonable output.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2681/

Use copy of bcc_helper.h from performance-diagnositics

---

.github/scripts/flake8_stbtrace.sh
.github/workflows/flake8.yml
bpf/standalone/zil.py
bpf/stbtrace/io.st
bpf/stbtrace/iscsi.st
bpf/stbtrace/nfs.st
bpf/stbtrace/vfs.st
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
cmd/estat.py
cmd/stbtrace.py
debian/control
lib/bcchelper.py

This converts all of the python 2 code to python 3.

Switch to Python 3

---

bpf/standalone/zil.py
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
cmd/estat.py

Due to[ changes in ftrace.h](https://github.com/torvalds/linux/commit/562e14f72292249e52e6346a9e3a30be652b0cf6) the bcc C code fails to compile for scripts including zfs headers.  
For example:  
$ sudo ./estat.py zil
In file included from /virtual/main.c:8:
In file included from /usr/src/zfs-5.3.0-26-generic/include/sys/zfs_vfsops.h:29:
In file included from /usr/src/zfs-5.3.0-26-generic/include/sys/dataset_kstats.h:30:
In file included from /usr/src/zfs-5.3.0-26-generic/include/sys/aggsum.h:22:
In file included from /usr/src/zfs-5.3.0-26-generic/include/sys/zfs_context.h:57:
In file included from /usr/src/zfs-5.3.0-26-generic/include/spl/sys/sunddi.h:32:
In file included from /usr/src/zfs-5.3.0-26-generic/include/spl/sys/vnode.h:29:
In file included from include/linux/syscalls.h:85:
In …

Compilation failures due to fentry issue

---

cmd/estat.py

closes #23
Please check if your PR fulfills the following requirements:
Please check the type of change your PR introduces:
Issue Number: 23
Throughput now normalized so that it is truly kb/s.   
Here is some output showing the throughput correctly reported: 
```
$ sudo ./cmd/estat.py zio  1
...
iops(/s)  avg latency(us)       stddev(us)  throughput(k/s)
write, syncw                                 8             2143          5498292              120
iops(/s)  throughput(k/s)
total                                        8              120
$ sudo ./cmd/estat.py zio  10
...
iops(/s)  avg latency(us)       stddev(us)  throughput(k/s)
write, asyncw                               23             1938          5616501              105
write, syncw                                11 …
```

Throughput values are not normalized

---

bpf/standalone/txg.py
cmd/estat.py

This is a port of the dtrace script : 
http://grok.delphix.com/xref/dlpx-app-5.3-stage/appliance/server/service/performance_playbook/txg.d
This is a little different than the existing estat scripts and there are a few new things to give extra scrutiny too.  
1) Event based profiling using bcc BPF_PERF_OUTPUT map. 
2) A perf event, the equivalent of a dtrace profiling probe
3) Using drgn python package to read zfs_dirty_data_max.
Here sample output.   I need to get on a loaded machine and verify the output when throttling and delays are an issue.  
Thu Jan 23 16:21:41 2020     100482  5025ms   214ms (99 pass 1)   2MB ( 0)    0us     0ms    0ms
Thu Jan 23 16:21:46 2020     100483  4909ms   114ms (97 pass 1)   1MB ( 0)    0us     0ms    0ms
Thu Jan 23 16:21:51 2020     100484  5226ms   179ms …

port txg dtrace script to ebpf

---

bpf/estat/backend-io.c
bpf/stbtrace/io.st

When running with the latest version of BCC (not yet merged into our repo), we see the following error when running the io stbtrace/estat programs:
```
$ sudo estat backend-io -a rpool 5
bpf: Failed to load program: Permission denied
0: (79) r6 = *(u64 *)(r1 +112)
1: (7b) *(u64 *)(r10 -8) = r6
2: (b7) r7 = 0
3: (7b) *(u64 *)(r10 -16) = r7
4: (7b) *(u64 *)(r10 -24) = r7
5: (7b) *(u64 *)(r10 -48) = r7
6: (bf) r3 = r6
7: (07) r3 += 192
8: (bf) r1 = r10
9: (07) r1 += -48
10: (b7) r2 = 8
11: (85) call bpf_probe_read#4
12: (79) r8 = *(u64 *)(r10 -48)
13: (85) call bpf_ktime_get_ns#5
14: (7b) *(u64 *)(r10 -40) = r0
15: (63) *(u32 *)(r10 -48) = r7
16: (bf) r3 = r6
17: (07) r3 += 68
18: (bf) r1 = r10
19: (07) r1 += -48
20: (b7) r2 = 4
21: (85) call bpf_probe_read#4
22: (61) r1 = *(u32 *)(r10 -48) …
```

Invalid mem errors when using latest BCC

---

cmd/nfs_threads.py
debian/control
debian/rules

Display NFS thread usage info along with NFS I/O context (for both v3 and v4 clients).
Output Sample:
```
packets  sockets threads threads metadata  read    read  write   write
arrived enqueued   woken   used     calls  iops thruput   iops thruput
4589        0    4589     25        16   273   3.6MB    212   2.6MB
4735        0    4735      8         1   287   3.8MB    212   2.7MB
4693        0    4693     10         0   280   3.7MB    216   2.7MB
4625        0    4625     15         0   278   3.7MB    212   2.6MB
4687        0    4687      7         1   285   3.8MB    210   2.6MB
4701        0    4701     12         0   285   3.8MB    215   2.7MB
```
Testing 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2649/
Confirmed that …

Add nfs_threads command

---

bpf/standalone/arc_prefetch.py
lib/bcc_helper.h
lib/bcchelper.py

See [DLPX-68394](https://jira.delphix.com/browse/DLPX-68394)
Here is sample output: 
02/12/20 - 17:21:40 UTC
prefetch hit count   : 21
prefetch miss count  : 17
prefetch read count  : 1
microseconds                                         arc read latency
[16, 32)                        9 |@@@@@@@@@@@@@@@@@@                      
[32, 64)                        6 |@@@@@@@@@@@@                            
[64, 128)                       3 |@@@@@                                   
microseconds                                    prefetch read latency
[16M, 32M)                      1 |@                                       
avg latency(us) …

Add arc_prefetch script.

---

cmd/stbtrace.py

Clean cherry-pick from master (commit 21b6666da2 ).
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3433/
Needed for picking up the phython3 commit.

stbtrace should have nonzero exit code on failure  [Backport of #17 to 6.0.3.0]

---

bpf/standalone/zil.py
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
cmd/estat.py

Clean cherry-pick of #33 
**Testing:**
ab-pre-push:  http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3455/
On image from above ab-pre-push, spot checked various estat commands and verified analytic probes are working.  No longer seeing the `fentry` compiler errors.

Compilation failures due to fentry issue [Backport of #33 to 6.0.3.0]

---

.github/scripts/flake8_stbtrace.sh
.github/workflows/flake8.yml
bpf/standalone/zil.py
bpf/stbtrace/io.st
bpf/stbtrace/iscsi.st
bpf/stbtrace/nfs.st
bpf/stbtrace/vfs.st
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
cmd/estat.py
cmd/stbtrace.py
debian/control
lib/bcchelper.py

A mostly clean cherry-pick.  Had to drop one unnecessary style cleanup since #21 has not yet landed in stage.
ab-pre-push is at: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3481/
On image from above^, spot checked estat and also verified the analytic probes are working

Switch to Python 3 [Backport of #9 to 6.0.3.0]

---

bpf/standalone/zil.py

The estat zil command fails to load with the unknown type errors as show below.  
```
$ sudo estat zil
In file included from <built-in>:3:
/virtual/include/bcc/helpers.h:47:9: warning: 'CC_USING_FENTRY' macro redefined [-Wmacro-redefined]
#define CC_USING_FENTRY
^
<command line>:6:9: note: previous definition is here
#define CC_USING_FENTRY 1
^
In file included from /virtual/main.c:9:
In file included from /usr/src/zfs-5.4.0-48-generic/include/sys/zfs_znode.h:30:
In file included from /usr/src/zfs-5.4.0-48-generic/include/sys/zfs_acl.h:35:
/usr/src/zfs-5.4.0-48-generic/include/sys/zfs_fuid.h:101:30: error: unknown type name 'zfsvfs_t'
```
There is also a warning about CC_USING_FENTRY that can be cleaned up.  The zil script is a standalone and sets up it's own bpf include path.   This …

DLPX-72430 Estat zil fails to run because of unknown types

---

bpf/standalone/arc_prefetch.py
bpf/standalone/txg.py
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
cmd/estat.py

This PR addresses warning messages like the following: 
```
In file included from <built-in>:3:
/virtual/include/bcc/helpers.h:47:9: warning: 'CC_USING_FENTRY' macro redefined [-Wmacro-redefined]
#define CC_USING_FENTRY
^
<command line>:7:9: note: previous definition is here
#define CC_USING_FENTRY 1
^
1 warning generated.
```
I executed all the scripts and do not see any warning messages or any new compilation issues.  
sudo ./estat.py backend-io 1
WARNING: kprobe: blk_start_request - not found
10/31/20 - 16:45:35 UTC
microseconds                                                   write 
[700, 800)                      1 |@                                       
[900, 1000) …

DLPX-72556 estat warning messages

---

bpf/estat/backend-io.c
bpf/estat/zpl.c
bpf/standalone/arc_prefetch.py
bpf/standalone/zil.py
bpf/stbtrace/io.st
bpf/stbtrace/iscsi.st
bpf/stbtrace/nfs.st
bpf/stbtrace/vfs.st
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
cmd/estat.py
lib/bcc_helper.h
lib/bcchelper.py

This PR backports several commits from master and should effectively sync up master.  
We need to coordinate with an update of bcc to work around the same issue we hit here updating master: 
[#36 Invalid mem errors when using latest BCC](https://github.com/delphix/performance-diagnostics/pull/36)
I tested this on a 6.0/stage machine with an updated bcc that Pavel set up by running all the estat and stbtrace scripts.  While not testing functionality of the scripts, this does make sure the tracing scripts compile and run. It is not clean as these known issues are present: 
[On 6.0.5, estat zpl and zvol subcommands are failing to compile](https://jira.delphix.com/browse/DLPX-72405)
[estat warning messages](https://jira.delphix.com/browse/DLPX-72556)   
sudo ./estat.py backend-io 1
In file …

Sync 6.0 Stage with master

---

bpf/estat/iscsi.c
bpf/estat/zpl.c
bpf/estat/zvol.c

closes #53, closes #54
1. The zvol script would not compile:
```
/usr/src/zfs-5.4.0-64-dx2021012602-7a44e1b99-generic/include/sys/zvol_impl.h:53:2: error: unknown type name 'dataset_kstats_t'
dataset_kstats_t        zv_kstat;       /* zvol kstats */
^
/virtual/main.c:168:3: warning: 'memcpy' will always overflow; destination buffer has size 5, but size argument is 6 [-Wfortify-source]
__builtin_memcpy(&axis, "sync", WRITE_LENGTH);
^
/virtual/main.c:171:3: warning: 'memcpy' will always overflow; destination buffer has size 5, but size argument is 6 [-Wfortify-source]
__builtin_memcpy(&axis, "async", WRITE_LENGTH);
```
There is an undefined symbol fixed by adding an include statment.   Additionally there are some warning messages involving the length of strings being passed to …

Update estat iscsi, zvol, and zpl scripts.

---

bpf/estat/iscsi.c
bpf/estat/zpl.c
bpf/estat/zvol.c
bpf/standalone/arc_prefetch.py
bpf/standalone/txg.py
bpf/stbtrace/zio.st
bpf/stbtrace/zpl.st
cmd/estat.py

This includes three issues:  
Update estat iscsi, zvol, and zpl scripts. (#55)
LPX-72556 estat warning messages (#52)
It was not a clean merge as the zvol.c script had extra definitions related to [this pr](https://github.com/delphix/performance-diagnostics/pull/42).  That was no longer needed for aws.  Additionally the version of zfs on stage sill uses uio_t so there is not need to change to zfs_uio_t.
I ran all the estat scripts and all compiled and executed though some had no events to record(as expected): 
```
sudo ./estat.py backend-io 1
WARNING: kprobe: blk_start_request - not found
02/03/21 - 22:52:17 UTC
microseconds                                                   write 
value range                 count ------------- Distribution …
```

Backport of estat updates for 6.0.7.0

---

bpf/standalone/zil.py

There are two bug fixes.  First, the zil script wouldn't compile on 6.1 due to changes in the zfs_write() paramters.   
```
sudo ./zil.py -c 10
/virtual/main.c:67:1: error: unknown type name 'uio_t'
uio_t *uio, int ioflag)
```
The uio paramter is never referenced so I made that of type void * to make it more robust.   Additionally instead of taking an inode as a parameter a znode is required.  Without this change the filtering by spa name does not work and no data is reported.   
Secondly, the average number of allocations was hardcoded to always return 10 for some unknown reason.   The allocations were being counted but then instead of computing an average, 10 was always used.  The real average is usually just under 1 and so zero is printed(perhaps 10 was added when debugging that and …

Zil issues

---

bpf/standalone/zil.py

This backport fixes a compilation error in the script and then replaces an average allocation stat with call counts. 
I verified that this runs on 6.0.8.0. 
```
$ sudo ./zil.py
^C04/02/21 - 22:50:13 UTC
latency                                                    allocation
[8, 16)                        23 |@@@@@@@@@@                              
[16, 32)                       68 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@            
[32, 64)                        4 |@@                                      
[64, 128)                       2 |@                                       
latency                                                       io wait
value range                 count …
```

Backport of Zil issues 

---

bpf/estat/zpl.c
bpf/standalone/arc_prefetch.py

The estat zpl and arc_prefetch scripts do not catch any data due to the inode parameter in zfs_read and zfs_write being replaced by a znode.  
With this change the scripts start producing output: 
```blewis@brad-trunk:~/ws/performance-diagnostics/cmd$ sudo ./estat.py zpl  4
04/23/21 - 21:13:28 UTC
microseconds                                          zfs_write async
[20, 30)                        5 |@@@                                     
[30, 40)                        3 |@@                                      
[40, 50)                       27 |@@@@@@@@@@@@@@@@@                       
[50, 60)                       18 |@@@@@@@@@@@                             
[60, 70) …
```

DLPX-75470 estat zpl and arc_prefetch scripts need znode parameter

---

cmd/nfs_threads.py

The `/usr/bin/nfs_thread`s script on the Delphix engine does not currently flush its output so redirecting it to a file results in an empty file. It is useful for Support to be able to capture this output when troubleshooting NFS issues.
To be able to match up the output with other estat data, it would also be useful to have it include timestamps on each line.
The following improvements were added to nfs_threads script
- Added timestamp to output
- Print header every 48 lines of output
- Added flush to print lines
- Accommodate an NFS server restart while script is running
- Added optional  --interval argument to supply sampling interval
- Fixed threads used calculation (was sometimes going negative)
- Fixed underflow in sockets-enqueued
ab-pre-push: …

DLPX-75405 nfs_threads script should flush output and include timestamps

---

bpf/estat/zpl.c
bpf/standalone/arc_prefetch.py

Minor merge conflict but this brings 6.0/stage up to date with master. 
I did some quick runs on 6.0/stage to make sure the scripts compile and run: 
```blewis@brad-stage-estat:~/ws/performance-diagnostics/cmd$ sudo ./estat.py zpl -a rpool 5
06/10/21 - 15:17:35 UTC
microseconds                                           zfs_read async
[0, 10)                       173 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10, 20)                        3 |@                                       
microseconds                                          zfs_write async
[0, 10)                       401 …
```

DLPX-75470 estat zpl and arc_prefetch scripts need znode parameter (#61)

---

debian/control

performance-diagnostics actually uses python3 rather than python, so we fix the dependencies accordingly.
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5585/
- Verified that estat works on Ubuntu 20.04, which only has python3.

TOOL-11731 performance-diagnostics: build-depends on python3-minimal instead of python-minimal

---

debian/control

Clean cherry-pick of: #66 
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5832/

TOOL-11951 [Backport of TOOL-11731] performance-diagnostics: build-depends on python3-minimal instead of python-minimal

---

cmd/estat.py

Clean cherry-pick.   
I verified that the help text contains the arc_prefetch section when run from the ws.
```
./estat.py -h
USAGE: ./estat.py -h
./estat.py [prog] [options]
Tool for running eBPF programs for monitoring performance of various I/O
related subsystems, focusing on I/O latency. Output can be displayed with
histograms of I/O broken down by size and type, depending on the provided
arguments.
OPTIONS:
-h    show this help message and exit
The subcommands listed in the following section share common options.
Each executes the specified tracing program for <duration> seconds,
displaying various histograms detailing the I/O latency as seen by the
particular subsystem.
estat backend-io    [options] <duration>
estat iscsi         [options] <duration>
estat metaslab-alloc [options] …
```

DLPX-72683 [Backport of DLPX-72683 to 6.0.12.0] estat utility's help text is missing documentation for arc_prefetch

---

bpf/estat/iscsi.c

Clean cherry-pick.  
Testing: 
I made sure the script compiles with no errors.

DLPX-77845 [Backport of DLPX-77532 to 6.0.12.0] The iscsi estat script needs to be fixed so it reports data correctly

---

bpf/estat/backend-io.c
bpf/stbtrace/io.st

**DESCRIPTION**
This commit fixes the disk io analytics collector an aws engines.  The stbtrace io script fails with the following error:  
```
$ sudo cmd/stbtrace.py io
cannot attach kprobe, probe entry may not exist
Failed to attach BPF program b'disk_io_done' to kprobe b'blk_account_io_completion'
```
Though the probe cannot attach, this function is still called in the linux_kernel_aws code:  
```
git grep blk_account_io_completion
block/blk-core.c:static void blk_account_io_completion(struct request *req, unsigned int bytes)
block/blk-core.c:       blk_account_io_completion(req, nr_bytes);
```
The call is from blk_update_request() which is called by blk_mq_end_request().
In the generic code we have the same lines plus an additional declaration in an include file (does removing this …

DLPX-78812 Disk IO analytics collector not running on aws

---

bpf/stbtrace/iscsi.st

Recently the estat iscsi script was overhauled.  The stbtrace script suffers from some of the same issues that the estat script had, most notably missing write events and reporting incorrect throughput.  This commit rewrites the probe functions in the iscsi stbtrace script.  It uses the same probe functions as the estat version.  They have different aggregate_data functions.  
For testing the output was compared to the estat output to verify it's correctness:  
```
$ sudo stbtrace iscsi 
{"t":"1639163735", "op":"read", "count":"4114", "avgLatency":"3892728", "throughput":"269090816", "latency":"{200000,7},{300000,20},{400000,35},{500000,49},{600000,90},{700000,121},{800000,165},{900000,156},{1000000,158},{2000000,1299},{3000000,643},{4000000,303},{5000000,165},{6000000,120},{7000000,107},{ …
```

DLPX-78745 Apply estat iscsi approach to stbtrace script

---

bpf/stbtrace/zpl.st

Akash found this while working on new stbtrace tests. 
```
$ sudo python3 /usr/bin/stbtrace zpl
/virtual/main.c:51:54: error: unknown type name 'uio_t'; did you mean 'uid_t'?
int zfs_read_start(struct pt_regs *ctx, void *inode, uio_t *uio)
^~~~~
uid_t
include/linux/types.h:32:26: note: 'uid_t' declared here
typedef __kernel_uid32_t        uid_t;
^
/virtual/main.c:57:20: error: member reference base type 'uid_t' (aka 'unsigned int') is not a structure or union
data.size = uio->uio_resid;
~~~^ ~~~~~~~~~
/virtual/main.c:65:55: error: unknown type name 'uio_t'; did you mean 'uid_t'?
int zfs_write_start(struct pt_regs *ctx, void *inode, uio_t *uio)
^~~~~
uid_t
include/linux/types.h:32:26: note: 'uid_t' declared here
typedef __kernel_uid32_t        uid_t;
^
/virtual/main.c:71:20: error: member …
```

DLPX-78891 stbtrace zpl fails due to uid_t

---

debian/control

This PR relates to https://github.com/delphix/appliance-build/pull/671 and add the `telegraf` package into our image so that we can build a new stat collection mechanism which will replace most of the `delphix-stat.service`.

TOOL-13470 add telegraf dependency to the performance-diagnostic package

---

debian/control

TOOL-13515 [Backport of TOOL-13470 to 6.0.14.0] add telegraf dependency to the performance-diagnostic package

---

debian/control

This reverts commit 8cd3f7a28d08dac751a3abd159acabfa8432ea28.

Revert "TOOL-13515 [Backport of TOOL-13470 to 6.0.14.0] add telegraf dependency to the performance-diagnostic package (#82)"

---

cmd/estat.py
debian/rules
telegraf/delphix-telegraf-service
telegraf/delphix-telegraf.service
telegraf/nfs-threads.sh
telegraf/perf_playbook
telegraf/telegraf.base
telegraf/telegraf.inputs.dose
telegraf/telegraf.inputs.playbook
telegraf/zcache-stats.sh
telegraf/zpool-iostat-o.sh

Initial addition of configuration and control files to enable performance metric collection using the Telegraf agent.
See also IDEA-2835 : Improving Support Bundle Performance Metrics
Includes:
- Service definition and startup script for "delphix-telegraf"
- Modified version of "estat" adding JSON output via a "-j" option
- A "perf_playbook" wrapper script to enable/disable enhanced collection
- Configuration file sections (combined on startup)
- Simple wrappers to facilitate parsing of "nfs_threads", "zpool iostat -o",
and "zcache stats -a" outputs
The service starts with a "base" set of metrics, but will include Object Storage
metrics when it is detected, and will include Performance Playbook commands
if that has been enabled (manually). The config is reassembled each startup.
File …

CP-8403 Adding Telegraf-based metric collection.

---

telegraf/perf_playbook
telegraf/telegraf.inputs.dose
telegraf/telegraf.inputs.playbook

Added a 30s restart delay to external commads invoked via the "execd" plugin

DLPX-82298 Telegraf needs a restart delay for external programs

---

telegraf/telegraf.base
telegraf/telegraf.inputs.playbook

Added entries for these two commands

DLPX-82457 Telegraf: add zio-queue and metaslab-alloc to playbook collection
